export const NAV = {
  auth: {
    login: 'Login',
    register: 'Register',
    forgotPassword: 'ForgotPassword',
  },
  tabs: {
    home: 'Home',
    trips: 'Trips',
    notifications: 'Notifications',
    earnings: 'Earnings',
    profile: 'Profile',
  },
  passenger: {
    dashboard: 'PassengerDashboard',
    searchDriver: 'SearchDriver',
    driverFound: 'DriverFound',
    tripTracking: 'TripTracking',
    tripDetails: 'TripDetails',
    reviewDriver: 'ReviewDriver',
    payments: 'Payments',
    addPaymentMethod: 'AddPaymentMethod',
    savedPlaces: 'SavedPlaces',
    editProfile: 'EditProfile',
    settings: 'Settings',
  },
  driver: {
    dashboard: 'DriverDashboard',
    rideRequest: 'RideRequest',
    activeTrip: 'ActiveTrip',
    tripDetails: 'DriverTripDetails',
    earningsDetail: 'EarningsDetail',
    vehicle: 'Vehicle',
    documents: 'Documents',
    reviews: 'DriverReviews',
    editProfile: 'DriverEditProfile',
    settings: 'DriverSettings',
  },
} as const;
